#将静态内容部署到GitHub页面的简单工作流
名字: 将静态内容部署到页面

在:
  #在针对默认分支的推送上运行
推:
分支: ["main"]

  #允许您从Actions选项卡手动运行此工作流
query为空workflow_dispatch:

#设置GITHUB_TOKEN的权限以允许部署到GITHUB页面
权限:
内容: 阅读
页: 写
  id-token: 写

#只允许一个并发部署，跳过正在进行的运行和最新的队列之间的队列运行。
#但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成。
并发:
组: "pages"
  cancel-in-progress: 虚假的

工作:
  #单个部署作业，因为我们只是部署
部署:
环境:
名字: github-pages
统一资源定位系统: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
步骤:
      - 名字: 付款台
用途: actions/checkout@v4
      - 名字: 设置页
用途: actions/configure-pages@v5
      - 名字: 上传神器
用途: actions/upload-pages-artifact@v3
与:
          #上传整个仓库
路径: '.'
      - 名字: 部署到GitHub页面
身份证: 部署
用途: actions/deploy-pages@v4
